### ISSUE TITLE
Change extensions concat

### ISSUE THREAD

**Issue by quimm2003** [NicolasPetton/xref-js2#18]
I suggest changing the concatenation of the file extension in _xref-js2--search-rg-get-args_ function.

From:

`(list "-g" (concat "*." ext))`

To:

`(list "-g" (concat "*" ext))`

The last one gives us more freedom to specify file extensions. For example, some of the files I work with everyday containing javascript have the extension "*_pie.php".

So to find definitions I'm forced to use the extension "php" which selects all files ending with ".php", giving me more candidates than those I need to search for.

**Comment by NicolasPetton** [comment]
@quimm2003 the manual file extension list has been replaced with the `--type' option in master, so I'm closing this issue.
