### ISSUE TITLE
Which functions are called for xref keybindings?

### ISSUE THREAD

**Issue by ReneFroger** [NicolasPetton/xref-js2#5]
Thanks for sharing this package! I will try it out soon!
As a typical Emacs user, I heavily customized my Emacs with the configuration file.

So I couldn't figure out which keybindings the xref typically use, and I couldn't find it in the source code of `xref`.

When trying <kbd>C-h k M-.</kbd>, it is mixed up with the Evil keybindings.

Could you tell me which functions are called for:

```
M-. Jump to definition
M-? Jump to references
M-, Pop back to where M-. was last invoked
```

Then I will bind it to another keys, to try this out!

**Comment by NicolasPetton** [comment]
> Could you tell me which functions are called for:
> 
> ```
> M-. Jump to definition
> ```

xref-find-definitions

> ```
> M-? Jump to references
> ```

xref-find-references

> ```
> M-, Pop back to where M-. was last invoked
> ```

pop-tag-mark
