### ISSUE TITLE
user-error: You are not in a project

### ISSUE THREAD

**Issue by fxfactorial** [NicolasPetton/xref-js2#8]
Getting this error when using `M-.`

**Comment by NicolasPetton** [comment]
xref-js2 will look for the root of a VC repository to know where to look for files (git, svn, etc).  It looks like you're not versioning your project.

Alternatively, you can setup projectile, which will also fix your problem.

**Comment by fxfactorial** [comment]
@NicolasPetton ah, got you. Thank you.
